### ISSUE TITLE
Separate Project Reviews from ordinary Prrrs.

### ISSUE THREAD

**Issue by mantinone** [LearnersGuild/prrr#102]
The system for project reviews has recently changed.

It is my understanding that Project Reviews are currently sorted in with regular Pull Request reviews.  (correct me if I'm wrong here.)

Since it is currently not possible to select specific PR's to review, I think it is a good idea for us to have a separate queue for project reviews.  We do not necessarily want people finding ordinary PR reviews when they are looking to do a project review between 6PM Friday and 10 AM Monday.  Also, we do not want people waiting for EOD Friday PR's to wait on project reviews from other people before they can get their last PR's reviewed.

(A possible solution is the ability to add tags to Prrr's.  I bring this up because I have heard several people mention this as a possibility)

**Comment by shereefb** [comment]
@deadlyicon we should prioritize this
