### ISSUE TITLE
If user has a Prrr claimed, should only show claimed Prrr table & one Prrr per user

### ISSUE THREAD

**Issue by deadlyicon** [LearnersGuild/prrr#14]

**Comment by shakalee14** [comment]
@thamaranth i'm going to start working on this
@deadlyicon

**Comment by DianaVashti** [comment]
When user logs in, if they do not have a Prrr claimed, they should only see the claim-a-Prrr component. If they already have a Prrr claimed, they should only see the Prrrs Claimed component. The user should only be able to claim one Prrr at a time.

**Comment by DianaVashti** [comment]
This is combined in one PR (#43) and is in progress
