### ISSUE TITLE
Code Review analytics

### ISSUE THREAD

**Issue by shereefb** [LearnersGuild/prrr#26]
There are four metrics that can show us the health of code reviews:

_Total code reviews last week
_Total code reviews per reviewer
_Longest time for PR to be reviewed last week
_Average time for PR to be claimed last week
_Average time for PR to be completed last week
_Total number of projects that requested reviews
_Average number of reviews requested per project

**MPV**

All these can be inferred from a table spit out into a csv file
Pull request, requester,reviewer,date_requested,date_claimed,date_completed

**Ideally**

There's an analytics page that calculates all the above. When calculating longest time and average times, it should not count evenings or weekends. If it's a publicly available analytics page that shows the numbers over the last 7 days it would be accessible to learners and that would be a great thing! It would acknowledge coaches for their work, and incentivize projects with lower than average review requests to raise their number

**If I had a Pony**

Report date-range can be selected
Adds: Average time from claim to complete, and longest time from claim to complete

**Comment by jrob8577** [comment]
Waiting on code review for two issues - still requires testing (sunday funday === no tdd), and we left ourselves the opportunity to add UI to specify date (stats default to last week unless they are averages).
![screen shot 2017-01-08 at 6 35 22 pm](https://cloud.githubusercontent.com/assets/838110/21756092/6539276e-d5d1-11e6-8484-a48f520d2e30.png)

**Comment by shereefb** [comment]
Beautiful👏🏽👏🏽👏🏽👏🏽
