### ISSUE TITLE
swap out table of pending Prrrs for "there are X prrrs waitring, click here to claim one"

### ISSUE THREAD

**Issue by deadlyicon** [LearnersGuild/prrr#33]
This means a coach can only claim the next available Prrr

**Comment by DianaVashti** [comment]
#43 WIP: Change Prrrs table to single bar with "There are X Prrrs open: Claim the next one?" button
https://github.com/GuildCrafts/prrr/pull/43

**Comment by deonna** [comment]
I see some drawbacks:

What if the next PR is 100% React, I've never used React, but still want to practice looking at and critiquing other folks' code? 

Another example to consider: has happened to me another time: after spending 30 minutes coaching a team through a solution, I'll see their PR pop up on Prrr. Because I have context, I can complete the review more quickly than someone else who is looking at it with fresh eyes.

Restricting a reviewer's options to the oldest PR on Prrr seems like it would:

1) Drastically reduce the rate of code review completion
2) Reduce code review opportunities for learners who want practice reviewing code, but don't feel well-rounded enough in their skills and would benefit from picking the review they want to do

**Comment by jrob8577** [comment]
@deonna I would suggest generalizing this request to include some context clues in the PR - allowing teams, for example, to include some tags that indicate tech stack, or maybe type of review/focus of review requested (brainstorming: wip, code quality, bug on line X, etc.).  I am leery of relying on a single person's knowledge of a PR to understand who should claim what next, and would rather try to crowdsource that somehow...  

Having said all that, I like the fact that learners who may not be ready for a PR of a certain type may get stuck with one - this creates an opportunity for collaboration on the PR with someone who has more knowledge, and an additional learning opportunity for that someone...

**Comment by deonna** [comment]
@jrob8577 - Interesting point about the opportunity to collaborate on the PR. My fear is that folks will see a review that they feel intimidated by, and won't seek out another person with that skill set to collaborate with them on that review. Maybe this is something that can be addressed directly by the Moderator if it starts to happen.

I'm interested to see what happens once these changes reach production -- perhaps the flow won't change much at all.

My worry is that these metrics:

_Longest time for PR to be reviewed (Goal: 8 hours)
_Average time for PR to be claimed / completed (Goal: 4 hours)

...will increase at the expense of these:

_Percentage of active projects that requested a review (Goal: 100)
_Average number of code review requests per project (Goal: 5)

We'll see!

**Comment by jrob8577** [comment]
@deonna Do we have the ability to obtain that data now?  Could be interesting to just start gathering data and A/B test over the next two or three weeks.

**Comment by deonna** [comment]
@jrob8577 - Agreed about starting to A/B test over the next few weeks.  AFAIK, we don't have the ability to obtain that data now (do we, @deadlyicon?). I imagine that once the metrics PRs are merged, this'll be a lot easier to put into practice. 

I'll open an issue for testing.

**Comment by jrob8577** [comment]
@deonna I know I wrote endpoints to retrieve the data for a specific period of time, but they're in that metrics PR I issued, and I think @deadlyicon had some changes that were going to get integrated into that PR before merging...  But the endpoints (and dashboard) theoretically exists.

**Comment by deadlyicon** [comment]
@deonna can your concerns be addressed by being asked for a code review outside of Prrr?

**Comment by deadlyicon** [comment]
@deonna we also might store who "unclaimed" a Prrr so you can claim a Prrr, see its not something you feel useful to comment on, unclaim it and be able to move onto the next available Prrr.

**Comment by deonna** [comment]
@deadlyicon - I really like the idea of leveraging who 'unclaimed' a Prrr to solve this problem.

How I'm envisioning it:

1) Someone sees a Prrr they don't find useful to comment on and unclaims it
2) The list of Prrrs they see after unclaiming is filters out that Prrr (and any others) the person unclaims
3)  The Prrr that was unclaimed by that particular user is still visible to other logged-in users

Does that sound like what you were suggesting?

**Comment by deadlyicon** [comment]
How I'm envisioning it:

0. you see "there are 12 PRs pending review, <button>click here to claim one</button>"
0. you click that button
0. you decide your review is not useful enough
0. you unclaim
0. you click claim again (and you get a different Prrr)

rinse and repeat.

**Comment by deadlyicon** [comment]
I think removing the ability to pick and choose who you review is critical.

**Comment by deonna** [comment]
@deadlyicon - I see - I think I was missing the fact that we were removing the list altogether (but my initial interpretation was aligned with yours on not being able to cherry pick).

Sounds like we're on the same page. Shall we open a new issue for this?
