### ISSUE TITLE
Use IDM to authenticate

### ISSUE THREAD

**Issue by jeffreywescott** [LearnersGuild/prrr#4]
This would allow you to get a valid Learners Guild JWT, along with the guild UUID for the given user, which could be useful to cross-check stats at some point.

**Comment by jeffreywescott** [comment]
@punitrathore can show you how. :-)

**Comment by deadlyicon** [comment]
@punitrathore I would love to pair on this. We could do it remote and I'll screen record it

**Comment by shakalee14** [comment]
did this already happen @punitrathore @deadlyicon
