### ISSUE TITLE
Archive of Completed Code Reviews

### ISSUE THREAD

**Issue by deonna** [LearnersGuild/prrr#72]
...so others (SEPs, other learners) can read them, learn from them, and make additional comments

IMO, this is necessary helpful in terms of skills assessment as well as being able to address these three questions:

- How are we measuring quality and efficacy of these reviews?
- Are we reviewing reviews? 
- Is there feedback on the reviews? 

Can we just have an "Archive" tab on the navbar, similar to the "Metrics" tab?

**Comment by shereefb** [comment]
Yes please. I would definitely benefit from that.
